[workspace]
members = [
  "runner",
  "graphics_lib",
  "001_starfield",
  "002_mengersponge",
  "003_snake",
  "004_purplerain",
  "005_spaceinvaders",
  "006_mitosis",
  "007_solarsystem",
  "010_mazegenerator"
]

resolver = "2"
default-members = ["runner"]
