[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies] 
graphics= {path="../../lib/graphics"}
math={path="../../lib/math"}
piston = "1.0.0" 
image="0.25.5"
piston_window="0.132.0"
