[package]
name = "mazegenerator"
version = "0.1.0"
edition = "2021"

[dependencies] 
graphics = {path="../lib/graphics"}
rand = "0.8.5"
piston = "1.0.0" 
pistoncore-window = "1.0.0"
pistoncore-glutin_window = "0.72.0" 
piston2d-opengl_graphics = "0.85.0"
